//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAIONDPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\NCSoft\\The Tower of AION\\")]
        public string InstallDirectory {
            get {
                return ((string)(this["InstallDirectory"]));
            }
            set {
                this["InstallDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\NCSoft\\The Tower of AION\\Chat.log")]
        public string ChatLogPath {
            get {
                return ((string)(this["ChatLogPath"]));
            }
            set {
                this["ChatLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName01 {
            get {
                return ((string)(this["FavoriteMemberName01"]));
            }
            set {
                this["FavoriteMemberName01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob01 {
            get {
                return ((string)(this["FavoriteMemberJob01"]));
            }
            set {
                this["FavoriteMemberJob01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName02 {
            get {
                return ((string)(this["FavoriteMemberName02"]));
            }
            set {
                this["FavoriteMemberName02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob02 {
            get {
                return ((string)(this["FavoriteMemberJob02"]));
            }
            set {
                this["FavoriteMemberJob02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName03 {
            get {
                return ((string)(this["FavoriteMemberName03"]));
            }
            set {
                this["FavoriteMemberName03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob03 {
            get {
                return ((string)(this["FavoriteMemberJob03"]));
            }
            set {
                this["FavoriteMemberJob03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName04 {
            get {
                return ((string)(this["FavoriteMemberName04"]));
            }
            set {
                this["FavoriteMemberName04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob04 {
            get {
                return ((string)(this["FavoriteMemberJob04"]));
            }
            set {
                this["FavoriteMemberJob04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName05 {
            get {
                return ((string)(this["FavoriteMemberName05"]));
            }
            set {
                this["FavoriteMemberName05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob05 {
            get {
                return ((string)(this["FavoriteMemberJob05"]));
            }
            set {
                this["FavoriteMemberJob05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName06 {
            get {
                return ((string)(this["FavoriteMemberName06"]));
            }
            set {
                this["FavoriteMemberName06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob06 {
            get {
                return ((string)(this["FavoriteMemberJob06"]));
            }
            set {
                this["FavoriteMemberJob06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName07 {
            get {
                return ((string)(this["FavoriteMemberName07"]));
            }
            set {
                this["FavoriteMemberName07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob07 {
            get {
                return ((string)(this["FavoriteMemberJob07"]));
            }
            set {
                this["FavoriteMemberJob07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName08 {
            get {
                return ((string)(this["FavoriteMemberName08"]));
            }
            set {
                this["FavoriteMemberName08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob08 {
            get {
                return ((string)(this["FavoriteMemberJob08"]));
            }
            set {
                this["FavoriteMemberJob08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName09 {
            get {
                return ((string)(this["FavoriteMemberName09"]));
            }
            set {
                this["FavoriteMemberName09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob09 {
            get {
                return ((string)(this["FavoriteMemberJob09"]));
            }
            set {
                this["FavoriteMemberJob09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName10 {
            get {
                return ((string)(this["FavoriteMemberName10"]));
            }
            set {
                this["FavoriteMemberName10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob10 {
            get {
                return ((string)(this["FavoriteMemberJob10"]));
            }
            set {
                this["FavoriteMemberJob10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName11 {
            get {
                return ((string)(this["FavoriteMemberName11"]));
            }
            set {
                this["FavoriteMemberName11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob11 {
            get {
                return ((string)(this["FavoriteMemberJob11"]));
            }
            set {
                this["FavoriteMemberJob11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName12 {
            get {
                return ((string)(this["FavoriteMemberName12"]));
            }
            set {
                this["FavoriteMemberName12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob12 {
            get {
                return ((string)(this["FavoriteMemberJob12"]));
            }
            set {
                this["FavoriteMemberJob12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName13 {
            get {
                return ((string)(this["FavoriteMemberName13"]));
            }
            set {
                this["FavoriteMemberName13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob13 {
            get {
                return ((string)(this["FavoriteMemberJob13"]));
            }
            set {
                this["FavoriteMemberJob13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName14 {
            get {
                return ((string)(this["FavoriteMemberName14"]));
            }
            set {
                this["FavoriteMemberName14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob14 {
            get {
                return ((string)(this["FavoriteMemberJob14"]));
            }
            set {
                this["FavoriteMemberJob14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName15 {
            get {
                return ((string)(this["FavoriteMemberName15"]));
            }
            set {
                this["FavoriteMemberName15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob15 {
            get {
                return ((string)(this["FavoriteMemberJob15"]));
            }
            set {
                this["FavoriteMemberJob15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName16 {
            get {
                return ((string)(this["FavoriteMemberName16"]));
            }
            set {
                this["FavoriteMemberName16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob16 {
            get {
                return ((string)(this["FavoriteMemberJob16"]));
            }
            set {
                this["FavoriteMemberJob16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName17 {
            get {
                return ((string)(this["FavoriteMemberName17"]));
            }
            set {
                this["FavoriteMemberName17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob17 {
            get {
                return ((string)(this["FavoriteMemberJob17"]));
            }
            set {
                this["FavoriteMemberJob17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName18 {
            get {
                return ((string)(this["FavoriteMemberName18"]));
            }
            set {
                this["FavoriteMemberName18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob18 {
            get {
                return ((string)(this["FavoriteMemberJob18"]));
            }
            set {
                this["FavoriteMemberJob18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName19 {
            get {
                return ((string)(this["FavoriteMemberName19"]));
            }
            set {
                this["FavoriteMemberName19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob19 {
            get {
                return ((string)(this["FavoriteMemberJob19"]));
            }
            set {
                this["FavoriteMemberJob19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName20 {
            get {
                return ((string)(this["FavoriteMemberName20"]));
            }
            set {
                this["FavoriteMemberName20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob20 {
            get {
                return ((string)(this["FavoriteMemberJob20"]));
            }
            set {
                this["FavoriteMemberJob20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName21 {
            get {
                return ((string)(this["FavoriteMemberName21"]));
            }
            set {
                this["FavoriteMemberName21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob21 {
            get {
                return ((string)(this["FavoriteMemberJob21"]));
            }
            set {
                this["FavoriteMemberJob21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName22 {
            get {
                return ((string)(this["FavoriteMemberName22"]));
            }
            set {
                this["FavoriteMemberName22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob22 {
            get {
                return ((string)(this["FavoriteMemberJob22"]));
            }
            set {
                this["FavoriteMemberJob22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName23 {
            get {
                return ((string)(this["FavoriteMemberName23"]));
            }
            set {
                this["FavoriteMemberName23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob23 {
            get {
                return ((string)(this["FavoriteMemberJob23"]));
            }
            set {
                this["FavoriteMemberJob23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName24 {
            get {
                return ((string)(this["FavoriteMemberName24"]));
            }
            set {
                this["FavoriteMemberName24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob24 {
            get {
                return ((string)(this["FavoriteMemberJob24"]));
            }
            set {
                this["FavoriteMemberJob24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName25 {
            get {
                return ((string)(this["FavoriteMemberName25"]));
            }
            set {
                this["FavoriteMemberName25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob25 {
            get {
                return ((string)(this["FavoriteMemberJob25"]));
            }
            set {
                this["FavoriteMemberJob25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName26 {
            get {
                return ((string)(this["FavoriteMemberName26"]));
            }
            set {
                this["FavoriteMemberName26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob26 {
            get {
                return ((string)(this["FavoriteMemberJob26"]));
            }
            set {
                this["FavoriteMemberJob26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName27 {
            get {
                return ((string)(this["FavoriteMemberName27"]));
            }
            set {
                this["FavoriteMemberName27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob27 {
            get {
                return ((string)(this["FavoriteMemberJob27"]));
            }
            set {
                this["FavoriteMemberJob27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName28 {
            get {
                return ((string)(this["FavoriteMemberName28"]));
            }
            set {
                this["FavoriteMemberName28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob28 {
            get {
                return ((string)(this["FavoriteMemberJob28"]));
            }
            set {
                this["FavoriteMemberJob28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName29 {
            get {
                return ((string)(this["FavoriteMemberName29"]));
            }
            set {
                this["FavoriteMemberName29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob29 {
            get {
                return ((string)(this["FavoriteMemberJob29"]));
            }
            set {
                this["FavoriteMemberJob29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName30 {
            get {
                return ((string)(this["FavoriteMemberName30"]));
            }
            set {
                this["FavoriteMemberName30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob30 {
            get {
                return ((string)(this["FavoriteMemberJob30"]));
            }
            set {
                this["FavoriteMemberJob30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName31 {
            get {
                return ((string)(this["FavoriteMemberName31"]));
            }
            set {
                this["FavoriteMemberName31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob31 {
            get {
                return ((string)(this["FavoriteMemberJob31"]));
            }
            set {
                this["FavoriteMemberJob31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName32 {
            get {
                return ((string)(this["FavoriteMemberName32"]));
            }
            set {
                this["FavoriteMemberName32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob32 {
            get {
                return ((string)(this["FavoriteMemberJob32"]));
            }
            set {
                this["FavoriteMemberJob32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName33 {
            get {
                return ((string)(this["FavoriteMemberName33"]));
            }
            set {
                this["FavoriteMemberName33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob33 {
            get {
                return ((string)(this["FavoriteMemberJob33"]));
            }
            set {
                this["FavoriteMemberJob33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName34 {
            get {
                return ((string)(this["FavoriteMemberName34"]));
            }
            set {
                this["FavoriteMemberName34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob34 {
            get {
                return ((string)(this["FavoriteMemberJob34"]));
            }
            set {
                this["FavoriteMemberJob34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName35 {
            get {
                return ((string)(this["FavoriteMemberName35"]));
            }
            set {
                this["FavoriteMemberName35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob35 {
            get {
                return ((string)(this["FavoriteMemberJob35"]));
            }
            set {
                this["FavoriteMemberJob35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName36 {
            get {
                return ((string)(this["FavoriteMemberName36"]));
            }
            set {
                this["FavoriteMemberName36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob36 {
            get {
                return ((string)(this["FavoriteMemberJob36"]));
            }
            set {
                this["FavoriteMemberJob36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName37 {
            get {
                return ((string)(this["FavoriteMemberName37"]));
            }
            set {
                this["FavoriteMemberName37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob37 {
            get {
                return ((string)(this["FavoriteMemberJob37"]));
            }
            set {
                this["FavoriteMemberJob37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName38 {
            get {
                return ((string)(this["FavoriteMemberName38"]));
            }
            set {
                this["FavoriteMemberName38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob38 {
            get {
                return ((string)(this["FavoriteMemberJob38"]));
            }
            set {
                this["FavoriteMemberJob38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName39 {
            get {
                return ((string)(this["FavoriteMemberName39"]));
            }
            set {
                this["FavoriteMemberName39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob39 {
            get {
                return ((string)(this["FavoriteMemberJob39"]));
            }
            set {
                this["FavoriteMemberJob39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName40 {
            get {
                return ((string)(this["FavoriteMemberName40"]));
            }
            set {
                this["FavoriteMemberName40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob40 {
            get {
                return ((string)(this["FavoriteMemberJob40"]));
            }
            set {
                this["FavoriteMemberJob40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName41 {
            get {
                return ((string)(this["FavoriteMemberName41"]));
            }
            set {
                this["FavoriteMemberName41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob41 {
            get {
                return ((string)(this["FavoriteMemberJob41"]));
            }
            set {
                this["FavoriteMemberJob41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName42 {
            get {
                return ((string)(this["FavoriteMemberName42"]));
            }
            set {
                this["FavoriteMemberName42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob42 {
            get {
                return ((string)(this["FavoriteMemberJob42"]));
            }
            set {
                this["FavoriteMemberJob42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName43 {
            get {
                return ((string)(this["FavoriteMemberName43"]));
            }
            set {
                this["FavoriteMemberName43"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob43 {
            get {
                return ((string)(this["FavoriteMemberJob43"]));
            }
            set {
                this["FavoriteMemberJob43"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName44 {
            get {
                return ((string)(this["FavoriteMemberName44"]));
            }
            set {
                this["FavoriteMemberName44"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob44 {
            get {
                return ((string)(this["FavoriteMemberJob44"]));
            }
            set {
                this["FavoriteMemberJob44"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName45 {
            get {
                return ((string)(this["FavoriteMemberName45"]));
            }
            set {
                this["FavoriteMemberName45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob45 {
            get {
                return ((string)(this["FavoriteMemberJob45"]));
            }
            set {
                this["FavoriteMemberJob45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName46 {
            get {
                return ((string)(this["FavoriteMemberName46"]));
            }
            set {
                this["FavoriteMemberName46"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob46 {
            get {
                return ((string)(this["FavoriteMemberJob46"]));
            }
            set {
                this["FavoriteMemberJob46"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName47 {
            get {
                return ((string)(this["FavoriteMemberName47"]));
            }
            set {
                this["FavoriteMemberName47"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob47 {
            get {
                return ((string)(this["FavoriteMemberJob47"]));
            }
            set {
                this["FavoriteMemberJob47"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberName48 {
            get {
                return ((string)(this["FavoriteMemberName48"]));
            }
            set {
                this["FavoriteMemberName48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteMemberJob48 {
            get {
                return ((string)(this["FavoriteMemberJob48"]));
            }
            set {
                this["FavoriteMemberJob48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveResultDirectory {
            get {
                return ((string)(this["SaveResultDirectory"]));
            }
            set {
                this["SaveResultDirectory"] = value;
            }
        }
    }
}
